# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/overlay/hsc_video.xdc

# Block Designs: bd/hsc_video/hsc_video.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video || ORIG_REF_NAME==hsc_video} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_concat_interrupts_0/hsc_video_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_concat_interrupts_0 || ORIG_REF_NAME==hsc_video_concat_interrupts_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_ps7_0_0/hsc_video_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_ps7_0_0 || ORIG_REF_NAME==hsc_video_ps7_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_xbar_0/hsc_video_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_xbar_0 || ORIG_REF_NAME==hsc_video_xbar_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_s00_regslice_2/hsc_video_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_s00_regslice_2 || ORIG_REF_NAME==hsc_video_s00_regslice_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_pc_1/hsc_video_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_pc_1 || ORIG_REF_NAME==hsc_video_auto_pc_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m00_regslice_2/hsc_video_m00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m00_regslice_2 || ORIG_REF_NAME==hsc_video_m00_regslice_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_pc_0/hsc_video_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_pc_0 || ORIG_REF_NAME==hsc_video_auto_pc_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m01_regslice_2/hsc_video_m01_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m01_regslice_2 || ORIG_REF_NAME==hsc_video_m01_regslice_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_ps7_0_axi_periph_0/hsc_video_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_ps7_0_axi_periph_0 || ORIG_REF_NAME==hsc_video_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk0_0/hsc_video_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==hsc_video_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk1_0/hsc_video_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==hsc_video_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_system_interrupts_0/hsc_video_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_system_interrupts_0 || ORIG_REF_NAME==hsc_video_system_interrupts_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_xbar_1/hsc_video_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_xbar_1 || ORIG_REF_NAME==hsc_video_xbar_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_s00_regslice_3/hsc_video_s00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_s00_regslice_3 || ORIG_REF_NAME==hsc_video_s00_regslice_3} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_pc_2/hsc_video_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_pc_2 || ORIG_REF_NAME==hsc_video_auto_pc_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m00_regslice_3/hsc_video_m00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m00_regslice_3 || ORIG_REF_NAME==hsc_video_m00_regslice_3} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m01_regslice_3/hsc_video_m01_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m01_regslice_3 || ORIG_REF_NAME==hsc_video_m01_regslice_3} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_cc_0/hsc_video_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_cc_0 || ORIG_REF_NAME==hsc_video_auto_cc_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m02_regslice_0/hsc_video_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m02_regslice_0 || ORIG_REF_NAME==hsc_video_m02_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_cc_1/hsc_video_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_cc_1 || ORIG_REF_NAME==hsc_video_auto_cc_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m03_regslice_0/hsc_video_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m03_regslice_0 || ORIG_REF_NAME==hsc_video_m03_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m04_regslice_0/hsc_video_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m04_regslice_0 || ORIG_REF_NAME==hsc_video_m04_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m05_regslice_0/hsc_video_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m05_regslice_0 || ORIG_REF_NAME==hsc_video_m05_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m06_regslice_0/hsc_video_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m06_regslice_0 || ORIG_REF_NAME==hsc_video_m06_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_cc_2/hsc_video_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_cc_2 || ORIG_REF_NAME==hsc_video_auto_cc_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m07_regslice_0/hsc_video_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m07_regslice_0 || ORIG_REF_NAME==hsc_video_m07_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_cc_3/hsc_video_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_cc_3 || ORIG_REF_NAME==hsc_video_auto_cc_3} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m08_regslice_0/hsc_video_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m08_regslice_0 || ORIG_REF_NAME==hsc_video_m08_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_m09_regslice_0/hsc_video_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_m09_regslice_0 || ORIG_REF_NAME==hsc_video_m09_regslice_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_cc_4/hsc_video_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_cc_4 || ORIG_REF_NAME==hsc_video_auto_cc_4} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axi_interconnect_0_0/hsc_video_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axi_interconnect_0_0 || ORIG_REF_NAME==hsc_video_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_xbar_2/hsc_video_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_xbar_2 || ORIG_REF_NAME==hsc_video_xbar_2} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_us_0/hsc_video_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_us_0 || ORIG_REF_NAME==hsc_video_auto_us_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_auto_pc_3/hsc_video_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_auto_pc_3 || ORIG_REF_NAME==hsc_video_auto_pc_3} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axi_mem_intercon_0/hsc_video_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axi_mem_intercon_0 || ORIG_REF_NAME==hsc_video_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axi_vdma_0/hsc_video_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axi_vdma_0 || ORIG_REF_NAME==hsc_video_axi_vdma_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axis_register_slice_0_0/hsc_video_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axis_register_slice_0_0 || ORIG_REF_NAME==hsc_video_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_color_convert_0/hsc_video_color_convert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_color_convert_0 || ORIG_REF_NAME==hsc_video_color_convert_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axi_gpio_hdmiin_0/hsc_video_axi_gpio_hdmiin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axi_gpio_hdmiin_0 || ORIG_REF_NAME==hsc_video_axi_gpio_hdmiin_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_color_swap_0_0/hsc_video_color_swap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_color_swap_0_0 || ORIG_REF_NAME==hsc_video_color_swap_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_dvi2rgb_0_0/hsc_video_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_dvi2rgb_0_0 || ORIG_REF_NAME==hsc_video_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_v_vid_in_axi4s_0_0/hsc_video_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hsc_video_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_vtc_in_0/hsc_video_vtc_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_vtc_in_0 || ORIG_REF_NAME==hsc_video_vtc_in_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_pixel_pack_0/hsc_video_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_pixel_pack_0 || ORIG_REF_NAME==hsc_video_pixel_pack_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axis_register_slice_0_1/hsc_video_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axis_register_slice_0_1 || ORIG_REF_NAME==hsc_video_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axis_register_slice_1_0/hsc_video_axis_register_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axis_register_slice_1_0 || ORIG_REF_NAME==hsc_video_axis_register_slice_1_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_color_convert_1/hsc_video_color_convert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_color_convert_1 || ORIG_REF_NAME==hsc_video_color_convert_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_axi_dynclk_0/hsc_video_axi_dynclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_axi_dynclk_0 || ORIG_REF_NAME==hsc_video_axi_dynclk_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_color_swap_0_1/hsc_video_color_swap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_color_swap_0_1 || ORIG_REF_NAME==hsc_video_color_swap_0_1} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_hdmi_out_hpd_video_0/hsc_video_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_hdmi_out_hpd_video_0 || ORIG_REF_NAME==hsc_video_hdmi_out_hpd_video_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/hsc_video_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_rgb2dvi_0_0 || ORIG_REF_NAME==hsc_video_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_v_axi4s_vid_out_0_0/hsc_video_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hsc_video_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_vtc_out_0/hsc_video_vtc_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_vtc_out_0 || ORIG_REF_NAME==hsc_video_vtc_out_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_pixel_proc_0/hsc_video_pixel_proc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_pixel_proc_0 || ORIG_REF_NAME==hsc_video_pixel_proc_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_pixel_unpack_0/hsc_video_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_pixel_unpack_0 || ORIG_REF_NAME==hsc_video_pixel_unpack_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==hsc_video_proc_sys_reset_pixelclk_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_xlconcat_0_0/hsc_video_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_xlconcat_0_0 || ORIG_REF_NAME==hsc_video_xlconcat_0_0} -quiet] -quiet

# IP: bd/hsc_video/ip/hsc_video_xlconcat_0_1/hsc_video_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hsc_video_xlconcat_0_1 || ORIG_REF_NAME==hsc_video_xlconcat_0_1} -quiet] -quiet

# XDC: bd/hsc_video/hsc_video_ooc.xdc
