# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.runs/synth_1/hsc_video_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.cache/wt [current_project]
set_property parent.project_path /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /mnt/sdc3/david/projs/hardware-software/part2/ip_cores [current_project]
update_ip_catalog
set_property ip_output_repo /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/hdl/hsc_video_wrapper.v
add_files /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/hsc_video.bd
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_ps7_0_0/hsc_video_ps7_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_xbar_0/hsc_video_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_s00_regslice_2/hsc_video_s00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_s00_regslice_2/hsc_video_s00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_pc_1/hsc_video_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m00_regslice_2/hsc_video_m00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m00_regslice_2/hsc_video_m00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_pc_0/hsc_video_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m01_regslice_2/hsc_video_m01_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m01_regslice_2/hsc_video_m01_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk0_0/hsc_video_rst_ps7_0_fclk0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk0_0/hsc_video_rst_ps7_0_fclk0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk0_0/hsc_video_rst_ps7_0_fclk0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk1_0/hsc_video_rst_ps7_0_fclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk1_0/hsc_video_rst_ps7_0_fclk1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rst_ps7_0_fclk1_0/hsc_video_rst_ps7_0_fclk1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_system_interrupts_0/hsc_video_system_interrupts_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_system_interrupts_0/hsc_video_system_interrupts_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_system_interrupts_0/hsc_video_system_interrupts_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_xbar_1/hsc_video_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_s00_regslice_3/hsc_video_s00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_s00_regslice_3/hsc_video_s00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_pc_2/hsc_video_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m00_regslice_3/hsc_video_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m00_regslice_3/hsc_video_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m01_regslice_3/hsc_video_m01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m01_regslice_3/hsc_video_m01_regslice_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_0/hsc_video_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_0/hsc_video_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_0/hsc_video_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m02_regslice_0/hsc_video_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m02_regslice_0/hsc_video_m02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_1/hsc_video_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_1/hsc_video_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_1/hsc_video_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m03_regslice_0/hsc_video_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m03_regslice_0/hsc_video_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m04_regslice_0/hsc_video_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m04_regslice_0/hsc_video_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m05_regslice_0/hsc_video_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m05_regslice_0/hsc_video_m05_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m06_regslice_0/hsc_video_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m06_regslice_0/hsc_video_m06_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_2/hsc_video_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_2/hsc_video_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_2/hsc_video_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m07_regslice_0/hsc_video_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m07_regslice_0/hsc_video_m07_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_3/hsc_video_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_3/hsc_video_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_3/hsc_video_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m08_regslice_0/hsc_video_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m08_regslice_0/hsc_video_m08_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m09_regslice_0/hsc_video_m09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_m09_regslice_0/hsc_video_m09_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_4/hsc_video_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_4/hsc_video_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_cc_4/hsc_video_auto_cc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_xbar_2/hsc_video_xbar_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_us_0/hsc_video_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_us_0/hsc_video_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_us_0/hsc_video_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_auto_pc_3/hsc_video_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_vdma_0/hsc_video_axi_vdma_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_vdma_0/hsc_video_axi_vdma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_vdma_0/hsc_video_axi_vdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_0_0/hsc_video_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_0_0/hsc_video_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_color_convert_0/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_gpio_hdmiin_0/hsc_video_axi_gpio_hdmiin_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_gpio_hdmiin_0/hsc_video_axi_gpio_hdmiin_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axi_gpio_hdmiin_0/hsc_video_axi_gpio_hdmiin_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_v_vid_in_axi4s_0_0/hsc_video_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_v_vid_in_axi4s_0_0/hsc_video_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_vtc_in_0/hsc_video_vtc_in_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_vtc_in_0/hsc_video_vtc_in_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_pixel_pack_0/constraints/pixel_pack_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_0_1/hsc_video_axis_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_0_1/hsc_video_axis_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_1_0/hsc_video_axis_register_slice_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_axis_register_slice_1_0/hsc_video_axis_register_slice_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_color_convert_1/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_hdmi_out_hpd_video_0/hsc_video_hdmi_out_hpd_video_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_hdmi_out_hpd_video_0/hsc_video_hdmi_out_hpd_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_hdmi_out_hpd_video_0/hsc_video_hdmi_out_hpd_video_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_v_axi4s_vid_out_0_0/hsc_video_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_v_axi4s_vid_out_0_0/hsc_video_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_vtc_out_0/hsc_video_vtc_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_vtc_out_0/hsc_video_vtc_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_pixel_proc_0/constraints/pixel_proc_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/hsc_video_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/constrs_1/imports/overlay/hsc_video.xdc
set_property used_in_implementation false [get_files /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/constrs_1/imports/overlay/hsc_video.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top hsc_video_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hsc_video_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hsc_video_wrapper_utilization_synth.rpt -pb hsc_video_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
