set_property SRC_FILE_INFO {cfile:/mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_ps7_0_0/hsc_video_ps7_0_0/hsc_video_ps7_0_0_in_context.xdc rfile:../../../hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_ps7_0_0/hsc_video_ps7_0_0/hsc_video_ps7_0_0_in_context.xdc id:1 order:EARLY scoped_inst:hsc_video_i/ps7_0} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_dvi2rgb_0_0/hsc_video_dvi2rgb_0_0/hsc_video_dvi2rgb_0_0_in_context.xdc rfile:../../../hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_dvi2rgb_0_0/hsc_video_dvi2rgb_0_0/hsc_video_dvi2rgb_0_0_in_context.xdc id:2 order:EARLY scoped_inst:hsc_video_i/video/hdmi_in/frontend/dvi2rgb_0} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/hsc_video_rgb2dvi_0_0/hsc_video_rgb2dvi_0_0_in_context.xdc rfile:../../../hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_rgb2dvi_0_0/hsc_video_rgb2dvi_0_0/hsc_video_rgb2dvi_0_0_in_context.xdc id:3 order:EARLY scoped_inst:hsc_video_i/video/hdmi_out/frontend/rgb2dvi_0} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/constrs_1/imports/overlay/hsc_video.xdc rfile:../../../hsc_video.srcs/constrs_1/imports/overlay/hsc_video.xdc id:4} [current_design]
current_instance hsc_video_i/ps7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 7.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 [get_ports {}]
current_instance
current_instance hsc_video_i/video/hdmi_in/frontend/dvi2rgb_0
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 6.060 [get_ports {}]
current_instance
current_instance hsc_video_i/video/hdmi_out/frontend/rgb2dvi_0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports -no_traverse PixelClk] -edges {1 2 3} -edge_shift {0.000 -2.424 -4.848} [get_ports -no_traverse {}]
current_instance
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVCMOS33} [get_ports IIC_1_scl_io]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports IIC_1_sda_io]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD TMDS_33} [get_ports hdmi_in_clk_n]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD TMDS_33} [get_ports hdmi_in_clk_p]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_n[0]}]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_p[0]}]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_n[1]}]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_p[1]}]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_n[2]}]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD TMDS_33} [get_ports {hdmi_in_data_p[2]}]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {hdmi_in_hpd[0]}]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports hdmi_in_ddc_scl_io]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports hdmi_in_ddc_sda_io]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD TMDS_33} [get_ports hdmi_out_clk_n]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD TMDS_33} [get_ports hdmi_out_clk_p]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[0]}]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[0]}]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[1]}]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[1]}]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[2]}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[2]}]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {hdmi_out_hpd[0]}]
