# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xci
# IP: The module: 'hsc_video_proc_sys_reset_pixelclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xci
# IP: The module: 'hsc_video_proc_sys_reset_pixelclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /mnt/sdc3/david/projs/hardware-software/part2/overlay/hsc_video/hsc_video.srcs/sources_1/bd/hsc_video/ip/hsc_video_proc_sys_reset_pixelclk_0/hsc_video_proc_sys_reset_pixelclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hsc_video_proc_sys_reset_pixelclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
